# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mutliple_loci_blast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='single_loci_blast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=100)),
                ('loci_name', models.CharField(choices=[('accD', 'accD'), ('matK', 'matK'), ('ndhJ', 'ndhJ'), ('rpoB', 'rpoB'), ('rpoC1', 'rpoC1'), ('ycf5', 'ycf5'), ('rbcL-a', 'rbcL-a'), ('trnH-psbA', 'trnH-psbA'), ('ITS1', 'ITS1'), ('ITS2', 'ITS2')], default='accD', max_length=15)),
                ('seq', models.TextField()),
            ],
        ),
    ]
