# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantID', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mutliple_loci_blast',
            new_name='multiple_loci_blast',
        ),
    ]
